"""Reconstruit les fichiers originaux et applique le bon filtre (garder si future ou sans date)."""

import sys
from pathlib import Path
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))
from agent.veille_nodes import _filter_old_entries

data_dir = Path(__file__).parent.parent / "data"

hackathons_raw = [
    {
        "nom": "RAISE Summit: AI Summit 2026 Paris",
        "date_debut": "",
        "date_fin": "",
        "lieu": "Paris, France",
        "description": "Le RAISE Summit est le plus influent sommet AI au monde",
        "url": "https://www.raisesummit.com/",
        "type": "Hackathon",
        "thematiques": "['IA']",
        "strategique": "Oui",
        "source": "https://www.raisesummit.com/",
        "score_strategique": 10,
        "raison": "Hackathon IA Paris 2026, organisé par RAISE",
    },
    {
        "nom": "AI & Digital Innovation in Medicine Summer School 2026",
        "date_debut": "",
        "date_fin": "",
        "lieu": "Paris, France",
        "description": "AI & Digital Innovation in Medicine Summer School 2026",
        "url": "https://www.prairie-psai.fr/",
        "type": "Hackathon",
        "thematiques": "['IA', 'éducation']",
        "strategique": "Oui",
        "source": "https://www.prairie-psai.fr/",
        "score_strategique": 10,
        "raison": "Hackathon IA Paris 2026, organisé par PRAIRIE",
    },
    {
        "nom": 'Hackathon Transversal : "L\'Intelligence Artificielle et ses enjeux sociétaux"',
        "date_debut": "",
        "date_fin": "",
        "lieu": "Paris, France",
        "description": "Hackathon Transversal sur l'IA",
        "url": "https://www.emlv.fr/en/discover/committed-responsible-school/",
        "type": "Hackathon",
        "thematiques": "['IA']",
        "strategique": "Oui",
        "source": "https://www.emlv.fr/",
        "score_strategique": 10,
        "raison": "Hackathon IA Paris, organisé par EMLV",
    },
    {
        "nom": "Master MINDS (AI)",
        "date_debut": "",
        "date_fin": "",
        "lieu": "Lyon, France",
        "description": "Master international en IA",
        "url": "https://www.insa-lyon.fr/fr/formation/master-minds-ai",
        "type": "Hackathon",
        "thematiques": "['IA', 'education']",
        "strategique": "Oui",
        "source": "https://www.insa-lyon.fr/",
        "score_strategique": 8,
        "raison": "Master IA Lyon 2026",
    },
    {
        "nom": "The 14th European Conference on Education",
        "date_debut": "09/07/2026",
        "date_fin": "13/07/2026",
        "lieu": "London, UK",
        "description": "The 14th European Conference on Education",
        "url": "https://ece.iafor.org/",
        "type": "Conference",
        "thematiques": "['education']",
        "strategique": "Oui",
        "source": "https://ece.iafor.org/",
        "score_strategique": 10,
        "raison": "Conférence éducation Londres 2026",
    },
    {
        "nom": "InfoComm 2026",
        "date_debut": "13/06/2026",
        "date_fin": "19/06/2026",
        "lieu": "Las Vegas, Nevada",
        "description": "Discover the latest audio visual tech at InfoComm 2026",
        "url": "https://www.infocommshow.org/",
        "type": "Salon",
        "thematiques": "['IA']",
        "strategique": "Non",
        "source": "https://www.infocommshow.org/",
        "score_strategique": 6,
        "raison": "Salon IA Las Vegas 2026",
    },
    {
        "nom": "EDUCAUSE Annual Conference 2026",
        "date_debut": "29/09/2026",
        "date_fin": "02/10/2026",
        "lieu": "Denver, CO",
        "description": "EDUCAUSE Annual Conference 2026",
        "url": "https://events.educause.edu/annual-conference",
        "type": "Conference",
        "thematiques": "['education']",
        "strategique": "Oui",
        "source": "https://events.educause.edu/",
        "score_strategique": 8,
        "raison": "Conférence éducation Denver 2026",
    },
    {
        "nom": "Innovative Learning Conference",
        "date_debut": "05/2026",
        "date_fin": "",
        "lieu": "San Francisco, California",
        "description": "Innovative Learning Conference",
        "url": "https://www.drmattlynch.com/10-edtech-conferences-you-should-attend-in-2026/",
        "type": "Conference",
        "thematiques": "['education']",
        "strategique": "Oui",
        "source": "https://www.drmattlynch.com/",
        "score_strategique": 8,
        "raison": "Conférence innovation éducation",
    },
    {
        "nom": "Future of Education Technology Conference",
        "date_debut": "06/2026",
        "date_fin": "",
        "lieu": "Las Vegas, Nevada",
        "description": "Future of Education Technology Conference",
        "url": "https://www.drmattlynch.com/10-edtech-conferences-you-should-attend-in-2026/",
        "type": "Conference",
        "thematiques": "['education']",
        "strategique": "Oui",
        "source": "https://www.drmattlynch.com/",
        "score_strategique": 8,
        "raison": "Conférence EdTech Las Vegas",
    },
    {
        "nom": "EdTech Week",
        "date_debut": "09/2026",
        "date_fin": "",
        "lieu": "New York City",
        "description": "EdTech Week: A Global Perspective",
        "url": "https://www.drmattlynch.com/10-edtech-conferences-you-should-attend-in-2026/",
        "type": "Conference",
        "thematiques": "['education']",
        "strategique": "Oui",
        "source": "https://www.drmattlynch.com/",
        "score_strategique": 8,
        "raison": "EdTech Week NYC 2026",
    },
    {
        "nom": "2026 Europe EdTech 200",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "The 2026 Europe Edtech 200",
        "url": "https://www.holoniq.com/notes/2026-europe-edtech-200",
        "type": "Hackathon",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.holoniq.com/",
        "score_strategique": 0,
        "raison": "",
    },
    {
        "nom": "Enterprise AI Europe 2026",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "we.CONECT Global Leaders Group",
        "url": "https://www.we-conect.com/events/enterprise-ai-europe-2026/",
        "type": "Hackathon",
        "thematiques": "['IA']",
        "strategique": "Non",
        "source": "https://www.we-conect.com/",
        "score_strategique": 0,
        "raison": "",
    },
    {
        "nom": "2026 International Conference on AI in Work, Innovation, Productivity and Skills",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "AI conference at OECD",
        "url": "https://www.oecd.org/en/events/2026/03/2026-international-conference-on-ai-in-work-innovation-productivity-and-skills.html",
        "type": "Conference",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.oecd.org/",
        "score_strategique": 0,
        "raison": "",
    },
    {
        "nom": "Міжнародні науково-практичні конференції 2026",
        "date_debut": "22/06/2026",
        "date_fin": "",
        "lieu": "Ліон, Франція",
        "description": "European conference for teachers and researchers",
        "url": "https://eu-conf.com/",
        "type": "Conference",
        "thematiques": "['IA', 'education']",
        "strategique": "Oui",
        "source": "https://eu-conf.com/",
        "score_strategique": 10,
        "raison": "Conférence européenne Lyon 2026",
    },
    {
        "nom": "EDGE AI Taipei 2026",
        "date_debut": "22/10/2026",
        "date_fin": "23/10/2026",
        "lieu": "Taipei, Europe",
        "description": "Edge AI conference",
        "url": "https://www.edgeaifoundation.org/",
        "type": "Hackathon",
        "thematiques": "['IA', 'education']",
        "strategique": "Oui",
        "source": "https://www.edgeaifoundation.org/",
        "score_strategique": 9,
        "raison": "Edge AI Taipei 2026",
    },
    {
        "nom": "AUTOMATE",
        "date_debut": "22/06/2026",
        "date_fin": "25/06/2026",
        "lieu": "Ville inconnue, Europe",
        "description": "Scaling Edge AI in the Modern Enterprise",
        "url": "https://www.edgeaifoundation.org/",
        "type": "Hackathon",
        "thematiques": "['IA', 'entreprise']",
        "strategique": "Oui",
        "source": "https://www.edgeaifoundation.org/",
        "score_strategique": 8,
        "raison": "Edge AI entreprise 2026",
    },
    {
        "nom": "Startup Mixer",
        "date_debut": "17/07/2026",
        "date_fin": "19/07/2026",
        "lieu": "Ville inconnue, Europe",
        "description": "Startup Mixer",
        "url": "https://www.edgeaifoundation.org/",
        "type": "Hackathon",
        "thematiques": "['IA', 'entreprise']",
        "strategique": "Oui",
        "source": "https://www.edgeaifoundation.org/",
        "score_strategique": 7,
        "raison": "Startup Mixer 2026",
    },
    {
        "nom": "Generative AI Summit 2026",
        "date_debut": "13/04/2026",
        "date_fin": "15/04/2026",
        "lieu": "London, UK",
        "description": "Europe's Leading Closed-Door Summit for Enterprise Leaders",
        "url": "https://www.aidataanalytics.network/events-generativeaisummit",
        "type": "Hackathon",
        "thematiques": "['IA']",
        "strategique": "Oui",
        "source": "https://www.aidataanalytics.network/",
        "score_strategique": 8,
        "raison": "Generative AI Summit Londres",
    },
    {
        "nom": "AI+IM Global Summit 2026",
        "date_debut": "28/04/2026",
        "date_fin": "30/04/2026",
        "lieu": "Baltimore, Maryland",
        "description": "AI+IM Global Summit by AIIM",
        "url": "https://www.aiim.org/aiim-global-summit-2026",
        "type": "Hackathon",
        "thematiques": "['IA', 'information management']",
        "strategique": "Oui",
        "source": "https://www.aiim.org/",
        "score_strategique": 9,
        "raison": "AI+IM Global Summit 2026",
    },
    {
        "nom": "Europe's AI & CX Leaders Are Meeting Here (2026)",
        "date_debut": "27/10/2026",
        "date_fin": "29/10/2026",
        "lieu": "Munich, Germany",
        "description": "Conversational AI and customer-centric approaches",
        "url": "https://conversationaltechsummit.com/",
        "type": "Hackathon",
        "thematiques": "['IA', 'customer experience']",
        "strategique": "Oui",
        "source": "https://conversationaltechsummit.com/",
        "score_strategique": 8,
        "raison": "AI & CX Summit Munich 2026",
    },
    {
        "nom": "Learning Technologies France 2027",
        "date_debut": "20/01/2027",
        "date_fin": "21/01/2027",
        "lieu": "Paris, France",
        "description": "L'évènement du futur de la formation professionnelle",
        "url": "https://www.learningtechnologiesfrance.com/",
        "type": "Hackathon",
        "thematiques": "['IA', 'education']",
        "strategique": "Oui",
        "source": "https://www.learningtechnologiesfrance.com/",
        "score_strategique": 10,
        "raison": "Learning Technologies Paris 2027",
    },
    {
        "nom": "Concours Digital InPulse 2026",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "Concours national start-up, smart mobility",
        "url": "https://www.dihnamic.eu/fr/actualites/",
        "type": "Hackathon",
        "thematiques": "['IA', 'education', 'mobilité intelligente']",
        "strategique": "Oui",
        "source": "https://www.dihnamic.eu/",
        "score_strategique": 8,
        "raison": "Digital InPulse 2026",
    },
    {
        "nom": "DIGITAL-2026-SKILLS-10-EDTECH - EU Funding",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "EU funding for EdTech startups",
        "url": "https://eufundingportal.eu/call-for-proposals-to-support-the-development-and-acceleration-of-edtech-solutions-through-financial-aid-incubation-programs-and-real-world-piloting/",
        "type": "Hackathon",
        "thematiques": "['EdTech', 'education']",
        "strategique": "Oui",
        "source": "https://eufundingportal.eu/",
        "score_strategique": 10,
        "raison": "EU EdTech funding 2026",
    },
    {
        "nom": "EdTech Accelerator | Digital Skills and Jobs Platform",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "Digital Europe Programme EdTech Accelerator",
        "url": "https://digital-skills-jobs.europa.eu/en/initiatives/funding/edtech-accelerator",
        "type": "Hackathon",
        "thematiques": "['EdTech', 'education']",
        "strategique": "Oui",
        "source": "https://digital-skills-jobs.europa.eu/",
        "score_strategique": 10,
        "raison": "EU EdTech Accelerator 2026",
    },
    {
        "nom": "Incubator and accelerator funding 2026: practical guide",
        "date_debut": "09/03/2026",
        "date_fin": "21/03/2026",
        "lieu": "Emilia-Romagna",
        "description": "Funding for incubators and accelerators",
        "url": "https://www.junto.space/en/post/funding-incubators-accelerators-2026",
        "type": "Hackathon",
        "thematiques": "['EdTech', 'education']",
        "strategique": "Oui",
        "source": "https://www.junto.space/",
        "score_strategique": 8,
        "raison": "Incubateur funding 2026",
    },
    {
        "nom": "Top 30 startup incubators and accelerators in the EU (2026)",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "Best incubators and accelerators in Europe",
        "url": "https://appwrite.io/blog/post/top-startup-accelerators-europe",
        "type": "Hackathon",
        "thematiques": "['EdTech', 'IA']",
        "strategique": "Non",
        "source": "https://appwrite.io/",
        "score_strategique": 0,
        "raison": "",
    },
    {
        "nom": "Top 77 EdTech Accelerators and Incubators (2026)",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "Best EdTech accelerators and incubators 2026",
        "url": "https://www.failory.com/startups/edtech-accelerators-incubators",
        "type": "Hackathon",
        "thematiques": "['EdTech']",
        "strategique": "Non",
        "source": "https://www.failory.com/",
        "score_strategique": 0,
        "raison": "",
    },
    {
        "nom": "EIC Accelerator - European Innovation Council",
        "date_debut": "",
        "date_fin": "",
        "lieu": "",
        "description": "EU funding for startups and SMEs",
        "url": "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
        "type": "Hackathon",
        "thematiques": "['EdTech', 'IA']",
        "strategique": "Non",
        "source": "https://eic.ec.europa.eu/",
        "score_strategique": 0,
        "raison": "",
    },
    {
        "nom": "IMPACT EdTech European Incubator-Accelerator Programme",
        "date_debut": "Juin 2026",
        "date_fin": "",
        "lieu": "",
        "description": "Funding Opportunities Opening in June 2026",
        "url": "https://www2.fundsforngos.org/latest-funds-for-ngos/applications-open-for-impact-edtech-european-incubator-accelerator-programme/",
        "type": "Hackathon",
        "thematiques": "['EdTech']",
        "strategique": "Oui",
        "source": "https://www2.fundsforngos.org/",
        "score_strategique": 8,
        "raison": "IMPACT EdTech incubator 2026",
    },
]

evenements_raw = [
    {
        "nom": "AI in Higher Education Summit 2026 \u2013 Paris",
        "type": "Conference",
        "date": "17/03/2026",
        "lieu": "Paris, France",
        "description": "Sommet IA dans l'éducation supérieure",
        "url": "https://escp.eu/ai",
        "thematiques": "['IA', 'éducation']",
        "strategique": "Oui",
        "source": "https://escp.eu/",
        "score_strategique": 10,
        "raison": "AI in Higher Education Summit Paris",
    },
    {
        "nom": "HR Tech Europe 2026",
        "type": "Conference",
        "date": "21/04/2026",
        "lieu": "RAI Amsterdam",
        "description": "HR technology event",
        "url": "https://www.hrtechnologyeurope.com/",
        "thematiques": "['RH', 'technologie']",
        "strategique": "Oui",
        "source": "https://www.hrtechnologyeurope.com/",
        "score_strategique": 9,
        "raison": "HR Tech Europe 2026",
    },
    {
        "nom": "EdTech World Forum 2026 - AI in Education Conference",
        "type": "Conference",
        "date": "2026",
        "lieu": "Londres, Royaume-Uni",
        "description": "AI in Education conference",
        "url": "https://edtechconferences.london/",
        "thematiques": "['IA', 'éducation']",
        "strategique": "Oui",
        "source": "https://edtechconferences.london/",
        "score_strategique": 8,
        "raison": "EdTech World Forum 2026",
    },
    {
        "nom": "Web Summit - The best tech conference in Europe",
        "type": "Conference",
        "date": "09/11/2026",
        "lieu": "Lisbonne, Portugal",
        "description": "Tech conference for startups",
        "url": "https://websummit.com/",
        "thematiques": "['tech', 'startups']",
        "strategique": "Oui",
        "source": "https://websummit.com/",
        "score_strategique": 9,
        "raison": "Web Summit Lisbon 2026",
    },
    {
        "nom": "AI and Business Innovation Summit",
        "type": "Conference",
        "date": "10/03/2027",
        "lieu": "London, Europe",
        "description": "AI business innovation summit",
        "url": "https://events.economistenterprise.com/business-innovation-summit/",
        "thematiques": "['IA', 'entreprise']",
        "strategique": "Oui",
        "source": "https://events.economistenterprise.com/",
        "score_strategique": 9,
        "raison": "AI Business Summit 2027",
    },
    {
        "nom": "GITEX AI EUROPE 2026",
        "type": "Salon",
        "date": "",
        "lieu": "Berlin, Europe",
        "description": "Europe's Boldest Tech Move Starts Here",
        "url": "https://www.gitexeurope.com/",
        "thematiques": "['IA', 'entreprise']",
        "strategique": "Oui",
        "source": "https://www.gitexeurope.com/",
        "score_strategique": 8,
        "raison": "GITEX AI Europe Berlin",
    },
    {
        "nom": "THE's global events",
        "type": "Conference",
        "date": "",
        "lieu": "Ville inconnue, Europe",
        "description": "THE global events for higher education",
        "url": "https://www.timeshighereducation.com/events/upcoming",
        "thematiques": "['IA', 'éducation']",
        "strategique": "Oui",
        "source": "https://www.timeshighereducation.com/",
        "score_strategique": 7,
        "raison": "THE global events",
    },
    {
        "nom": "Artificial intelligence and earth observation: From innovation to services",
        "type": "Conference",
        "date": "06/03/2026",
        "lieu": "Bruxelles, Belgique",
        "description": "AI and earth observation workshop",
        "url": "https://defence-industry-space.ec.europa.eu/artificial-intelligence-and-earth-observation-innovation-services-2026-03-09_en",
        "thematiques": "['IA', 'terre observation']",
        "strategique": "Oui",
        "source": "https://defence-industry-space.ec.europa.eu/",
        "score_strategique": 7,
        "raison": "AI earth observation Brussels",
    },
    {
        "nom": "PIA Acad\u00e9mie Num\u00e9rique - Cned",
        "type": "Conference",
        "date": "",
        "lieu": "",
        "description": "PIA Académie numérique France 2030",
        "url": "https://www.cned.fr/notre-methode/pia-academie-numerique",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.cned.fr/",
        "score_strategique": 3,
        "raison": "Pas de date précise",
    },
    {
        "nom": "Epitech, l'\u00c9cole de l'excellence informatique",
        "type": "Conference",
        "date": "",
        "lieu": "",
        "description": "Epitech IT school",
        "url": "https://www.epitech.eu/",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.epitech.eu/",
        "score_strategique": 3,
        "raison": "Pas de date précise",
    },
    {
        "nom": "Accueil | \u00e9duscol | Minist\u00e8re de l'\u00c9ducation nationale",
        "type": "Conference",
        "date": "",
        "lieu": "",
        "description": "Education ministry resources",
        "url": "http://www.eduscol.education.fr/",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "http://www.eduscol.education.fr/",
        "score_strategique": 3,
        "raison": "Pas de date précise",
    },
    {
        "nom": "Semaine mondiale de la Francophonie Scientifique",
        "type": "Conference",
        "date": "",
        "lieu": "",
        "description": "Semaine mondiale Francophonie Scientifique",
        "url": "https://www.auf.org/",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.auf.org/",
        "score_strategique": 3,
        "raison": "",
    },
    {
        "nom": "L'Expresso du jour",
        "type": "Conference",
        "date": "",
        "lieu": "",
        "description": "Education news",
        "url": "https://www.cafepedagogique.net/",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.cafepedagogique.net/",
        "score_strategique": 3,
        "raison": "",
    },
    {
        "nom": "Appel \u00e0 projets France2030 : Transition num\u00e9rique de la Culture",
        "type": "Competition",
        "date": "9 juin 2026",
        "lieu": "",
        "description": "France2030 call for projects",
        "url": "https://www.dihnamic.eu/fr/actualites/",
        "thematiques": "['IA', 'education']",
        "strategique": "Oui",
        "source": "https://www.dihnamic.eu/",
        "score_strategique": 10,
        "raison": "France2030 appel à projets",
    },
    {
        "nom": "Webinaire #28 - L'accompagnement au changement",
        "type": "Webinar",
        "date": "3 juin 2026",
        "lieu": "",
        "description": "Webinar on AI in business",
        "url": "https://www.dihnamic.eu/fr/actualites/",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.dihnamic.eu/",
        "score_strategique": 3,
        "raison": "",
    },
    {
        "nom": "L'Expresso Bac 2026 : tous les sujets de spécialit\u00e9 (jour 1)",
        "type": "Conference",
        "date": "16 juin 2026",
        "lieu": "",
        "description": "Bac 2026 subjects",
        "url": "https://www.cafepedagogique.net/",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.cafepedagogique.net/",
        "score_strategique": 3,
        "raison": "",
    },
    {
        "nom": "ANALYSE du sujet du bac de philosophie 2026",
        "type": "Conference",
        "date": "16 juin 2026",
        "lieu": "",
        "description": "Bac philosophy analysis",
        "url": "https://www.cafepedagogique.net/",
        "thematiques": "['IA', 'education']",
        "strategique": "Non",
        "source": "https://www.cafepedagogique.net/",
        "score_strategique": 3,
        "raison": "",
    },
    {
        "nom": "Top Edutech Accelerators & VCs (2026) - Open Deadlines",
        "type": "Conference",
        "date": "",
        "lieu": "",
        "description": "Edutech startup programs and VCs",
        "url": "https://incubatorlist.com/best-edutech-startup-accelerators-incubators-and-vcs",
        "thematiques": "['EdTech', 'education']",
        "strategique": "Non",
        "source": "https://incubatorlist.com/",
        "score_strategique": 5,
        "raison": "EdTech accelerators list",
    },
    {
        "nom": "EuraTechnologies, Incubateur et Acc\u00e9l\u00e9rateur de startups europ\u00e9en",
        "type": "Conference",
        "date": "03/06/2026",
        "lieu": "Lieu non spécifié",
        "description": "Candidatures ouvertes jusqu'au 22 juin 2026",
        "url": "https://www.euratechnologies.com/",
        "thematiques": "['EdTech']",
        "strategique": "Oui",
        "source": "https://www.euratechnologies.com/",
        "score_strategique": 8,
        "raison": "EuraTechnologies incubator",
    },
    {
        "nom": "Startup Grants in Portugal",
        "type": "Conference",
        "date": "02/03/2026",
        "lieu": "Portugal",
        "description": "Startup Grants in Portugal",
        "url": "https://blog.mean.ceo/startup-grants-portugal-news-march-2026/",
        "thematiques": "['EdTech', 'IA']",
        "strategique": "Oui",
        "source": "https://blog.mean.ceo/",
        "score_strategique": 6,
        "raison": "Startup grants Portugal",
    },
]

print(f"Original: {len(hackathons_raw)} hackathons, {len(evenements_raw)} evenements")

h_names_before = {h["nom"] for h in hackathons_raw}
e_names_before = {e["nom"] for e in evenements_raw}

hackathons = _filter_old_entries(hackathons_raw, ["date_debut", "date_fin"])
evenements = _filter_old_entries(evenements_raw, ["date"])

h_names_after = {h["nom"] for h in hackathons}
e_names_after = {e["nom"] for e in evenements}

print(f"Apres filtre: {len(hackathons)} hackathons, {len(evenements)} evenements")

removed_h = h_names_before - h_names_after
removed_e = e_names_before - e_names_after

if removed_h:
    print(f"\nHackathons retires ({len(removed_h)}):")
    for r in sorted(removed_h):
        print(f"  - {r}")
if removed_e:
    print(f"\nEvenements retires ({len(removed_e)}):")
    for r in sorted(removed_e):
        print(f"  - {r}")

df_h = pd.DataFrame(hackathons)
df_e = pd.DataFrame(evenements)

df_h.to_csv(data_dir / "final_hackathons.csv", index=False, encoding="utf-8-sig")
df_e.to_csv(data_dir / "final_evenements.csv", index=False, encoding="utf-8-sig")

with pd.ExcelWriter(data_dir / "final_complete.xlsx", engine="openpyxl") as writer:
    df_h.to_excel(writer, sheet_name="Hackathons", index=False)
    df_e.to_excel(writer, sheet_name="Evenements", index=False)

print(f"\nExporte: {data_dir / 'final_complete.xlsx'}")
print(
    f"Total: {len(df_h)} hackathons + {len(df_e)} evenements = {len(df_h) + len(df_e)}"
)
